In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_excel(r'D:\Projects\Smart Customer Support Ticket Router - NLP\Dataset\customer_support_tickets_200k.xlsx')

#### 1. Asking Basic Questions

These checks help us understand size, structure, data types, missing values, duplicates, and basic mathematical summaries.

In [21]:
df.shape

(200000, 30)

In [22]:
df.head()

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,...,ticket_resolved_date,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,...,2023-05-20,No,Yes,MacOS,Edge,PayPal,French,Afternoon,4,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,...,2024-01-19,Yes,Yes,Windows,Firefox,PayPal,English,Afternoon,2,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,...,2022-12-05,Yes,Yes,Windows,Safari,Bank Transfer,French,Morning,4,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,...,2024-04-04,Yes,No,Windows,Chrome,Credit Card,Spanish,Afternoon,7,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,...,2024-08-24,Yes,No,Linux,NaN,Debit Card,Spanish,Evening,3,Corporate

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  datetime64[ns]
 20  ticket_resolved_date         200000 non-null  datetime64[ns]
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      159977 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(6), object(20)
memory usage: 45.8+ MB

In [53]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
product                            0
category                           0
issue_description                  0
resolution_notes                   0
priority                           0
status                             0
channel                            0
region                             0
customer_age                       0
customer_gender                    0
subscription_type                  0
customer_tenure_months             0
previous_tickets                   0
customer_satisfaction_score        0
first_response_time_hours          0
resolution_time_hours              0
ticket_created_date                0
ticket_resolved_date               0
escalated                          0
sla_breached                       0
operating_system                   0
browser                        40023
payment_method                     0
language                           0
preferred_contact_time             0
issue_complexity_score             0
customer_segment                   0
dtype: int64

In [25]:
df['browser'] = df['browser'].fillna("Unknown")

In [26]:
df.isnull().sum().sum()

np.int64(0)

In [27]:
df.describe()

,ticket_id,customer_age,customer_tenure_months,previous_tickets,customer_satisfaction_score,first_response_time_hours,resolution_time_hours,ticket_created_date,ticket_resolved_date,issue_complexity_score
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000,200000,200000.000000
mean,100000.500000,46.469040,30.377675,9.992115,3.001065,36.309180,120.539718,2023-07-02 08:38:31.776000,2023-07-09 08:50:57.839999744,5.501365
min,1.000000,18.000000,1.000000,0.000000,1.000000,0.500000,1.000000,2022-01-01 00:00:00,2022-01-01 00:00:00,1.000000
25%,50000.750000,32.000000,15.000000,5.000000,2.000000,18.460000,60.810000,2022-10-01 00:00:00,2022-10-08 00:00:00,3.000000
50%,100000.500000,46.000000,30.000000,10.000000,3.000000,36.310000,120.450000,2023-07-02 00:00:00,2023-07-09 00:00:00,6.000000
75%,150000.250000,61.000000,45.000000,15.000000,4.000000,54.220000,180.260000,2024-04-02 00:00:00,2024-04-09 00:00:00,8.000000
max,200000.000000,75.000000,60.000000,20.000000,5.000000,72.000000,240.000000,2024-12-31 00:00:00,2025-01-14 00:00:00,10.000000
std,57735.171256,16.754304,17.326224,6.053142,1.412273,20.654575,68.969143,NaN,NaN,2.875587

In [54]:
df.describe(include = "object")

,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,region,customer_gender,subscription_type,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,customer_segment
count,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000,200000
unique,400,191751,10,10,10,10,4,5,5,6,3,4,2,2,5,5,5,6,4,3
top,Jessica Rodriguez,john.gonzalez711@gmail.com,Billing System,Feature Request,There seems to be a discrepancy in my billing statement for this month.,We have reset the account credentials and advised the customer to retry login.,High,In Progress,Web Form,Africa,Other,Free,Yes,Yes,Android,Safari,Crypto,Japanese,Morning,Individual
freq,568,4,20111,20169,20232,20141,50241,40065,40090,33576,66795,50147,100421,100043,40141,40156,40274,33620,50384,67098

In [55]:
df["category"].value_counts()

category
Feature Request              20169
Subscription Cancellation    20096
Performance Issue            20074
Security Concern             20040
Login Issue                  20002
Payment Problem              19997
Bug Report                   19981
Refund Request               19900
Data Sync Issue              19877
Account Suspension           19864
Name: count, dtype: int64

In [ ]:
# category distribution is highly balanced with each category contributing approximately 10% of the total samples
df["category"].value_counts(normalize=True) * 100

category
Feature Request              10.0845
Subscription Cancellation    10.0480
Performance Issue            10.0370
Security Concern             10.0200
Login Issue                  10.0010
Payment Problem               9.9985
Bug Report                    9.9905
Refund Request                9.9500
Data Sync Issue               9.9385
Account Suspension            9.9320
Name: proportion, dtype: float64

In [58]:
df['priority'].value_counts()

priority
High      50241
Urgent    50143
Medium    49854
Low       49762
Name: count, dtype: int64

In [ ]:
# priority distribution is also highly balanced with each category contributing approximately 25% of the total samples
df['priority'].value_counts(normalize = True) * 100

priority
High      25.1205
Urgent    25.0715
Medium    24.9270
Low       24.8810
Name: proportion, dtype: float64

In [71]:
# we can clearly see that, our dataset is not well labelled. If the 'issue_description' is same than the 'category' must also be same. But in this dataset as you can see, if the 'issue_description' is same than the 'category' is getting differ
df[['issue_description', 'category']].sample(5)

,issue_description,category
144529,I am unable to access my account after entering the correct credentials.,Security Concern
34686,There seems to be a discrepancy in my billing statement for this month.,Bug Report
142649,I am unable to access my account after entering the correct credentials.,Payment Problem
24430,I am unable to access my account after entering the correct credentials.,Performance Issue
40037,The application crashes whenever I try to upload a file.,Data Sync Issue

In [72]:
# from this we can interpret that, for 1 'issue_description', there are total '10' categories which cannot be possible in real world.
df.groupby('issue_description')['category'].nunique().sort_values(ascending=False)

issue_description
I am experiencing very slow performance while using the dashboard.                 10
I am unable to access my account after entering the correct credentials.           10
I found a bug in the latest update affecting report generation.                    10
I would like to request a refund for the recent charge.                            10
My subscription was cancelled without my request and I need clarification.         10
The application crashes whenever I try to upload a file.                           10
The payment was deducted from my bank account but the transaction shows failed.    10
The system is not syncing data across devices properly.                            10
There seems to be a discrepancy in my billing statement for this month.            10
Two-factor authentication codes are not being delivered to my phone.               10
Name: category, dtype: int64

In [86]:
df['issue_description'].nunique()

10

In [79]:
pd.crosstab(df['issue_description'], df['category'], normalize = "index").head(5)

category,Account Suspension,Bug Report,Data Sync Issue,Feature Request,Login Issue,Payment Problem,Performance Issue,Refund Request,Security Concern,Subscription Cancellation
issue_description,,,,,,,,,,
I am experiencing very slow performance while using the dashboard.,0.101727,0.102979,0.098824,0.097021,0.099625,0.100776,0.100726,0.099574,0.098073,0.100676
I am unable to access my account after entering the correct credentials.,0.100613,0.099816,0.100165,0.098270,0.096475,0.102508,0.098320,0.098619,0.102807,0.102408
I found a bug in the latest update affecting report generation.,0.098809,0.100166,0.100116,0.103180,0.097955,0.098006,0.099010,0.103984,0.100618,0.098156
I would like to request a refund for the recent charge.,0.097107,0.099810,0.101962,0.104265,0.099359,0.099660,0.102613,0.096206,0.098759,0.100260
My subscription was cancelled without my request and I need clarification.,0.098885,0.100392,0.097630,0.101195,0.100392,0.100743,0.100793,0.100793,0.097780,0.101396

#### Observation
- During exploratory data analysis, it was observed that the dataset contained only 10 unique issue descriptions repeated across all ticket categories.
- Crosstab analysis revealed that identical issue descriptions were uniformly distributed among categories, indicating severe label inconsistency.
- Since supervised learning requires a meaningful relationship between features and labels, the dataset was deemed unsuitable for text classification tasks.