In [12]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [3]:
df = pd.read_csv('data.csv')

In [19]:
df.sample(5)

,Document,Topic_group,text_length
5555,for support hi guys gotten feedback client please let say makes sense steps hi re calls offices these work remote session enable id id calls advise externally federate intercompany calls working told how maintain means leave equivalent please,Hardware,38
36797,connection issues connection issues hello yesterday experienced issues via cable were also resolved due thanks,Hardware,15
4744,release card for leaver card leaver si predate va sis,Access,10
41076,oracle fusion time logged pre issue sent tuesday fusion logged pre issue hello we would be assist with call please use for any enquiries ensure proper tracking list could you please rise ticket for request below kind regards engineer en sent tuesday fusion logged pre issue dear engineers have issue with before before switch think looked wanted fix one by myself managed get error how should look correctly for mon wed per for mon wed per for per annual leave for mon public holiday for per for per could you please help fix thanks head,HR Support,95
43906,access to unvoiced receipt report sent thursday february access receipt report hi please rise ticket thank you best regards analyst en sent wednesday february access receipt report hi trying run below report seems have access could you please check why should have access reports thanks kind regards accountant ext en,Hardware,50

In [17]:
df.loc[df['Topic_group'] == 'Hardware']

,Document,Topic_group,text_length
0,connection with icon icon dear please setup icon per icon engineers please let other details needed thanks lead,Hardware,18
2,requesting for meeting requesting meeting hi please help follow equipments cable pc cord plug,Hardware,14
6,prod servers tunneling prod tunneling va la tunneling la host si la si host host cards port name bytes bytes seq bytes seq statistics packets transmitted received packet loss avg bytes bytes seq bytes seq tuesday pm acre re tunneling si pm acre re tunneling extended object host extended host extended object host range extended host range administrator re sector pm acre re tunneling va la si la tunneling design lead ext friday pm re tunneling va extended object host extended host administrator re sector pm tunneling va la tunneling users pinging bytes bytes bytes bytes bytes design lead ext con care pot partial strict si pot ale care va la contains proprietary information which legally privileged unauthorized dissemination prohibited intended recipient views addressing transmission error has misdirected please notify author by replying intended recipient must disclose distribute copy print rely,Hardware,141
10,laptop connected on request rebuild connected rebuild hi please provide order debug sip trunk gateway wireless wired connected regards,Hardware,19
18,invitation to cloud strategy workshop february manchester invitation strategy workshop february manchester workshop forward colleague results campaign workshop reminder content workshop reminder ca cs dad ca trouble viewing view results campaign workshop reminder content workshop reminder cs dad ca assets images azure cs dad ca azure join cs dad ca manchester discuss journey unleash benefits powered by azure workshop control optimise strategy tickets cs dad ca february discussing best working opportunities digital give tools how embrace perfect environment wednesday february where sir busby way manchester further information found control optimise strategy tickets cs dad ca please note places join workshop manchester february control optimise strategy tickets cs dad ca make february workshop interest march where street campus birmingham join workshop birmingham control optimise strategy tickets cs dad ca assets images footer cs dad ca action campaign workshop reminder content workshop reminder ca cs dad ca road bb sr,Hardware,148
...,...,...,...
47825,for issues sent friday july for hi below issue something we can about can we raise ticket investigate please please be aware client raising cannot be process solving issue meantime we be using additional conference tool there immediate impact for thanks sent friday july re for hi main issue serious latency sometimes can be few seconds behind conversation made more difficult when we have way conversations between ny using android phone also via think client issue though seem more likely be infrastructure can recommend free cross platform integrated with slack any event we can continue using since was almost impossible for colleagues ny communicate with yesterday can suggest we use until issue with ironed out july wrote hi indeed we can use other tools but maybe we can look why working for for you help raising ticket our fix problem what know for works excellent clicking link invite letting default browser install for voice calls does require have for installed some questions help understanding situation you connecting for your phone your computer using link provided app if connecting computer you using or or meantime following up with if there concerns related having other installed computers sorry but we strict with rules for sake our clients too sent thursday july for hi we having issue with latency poor sounds quality using for have asked use conference but say corporate policy use possible permission use thanks,Hardware,234
47827,bandwidth problems sent thursday july bandwidth problems hello you already know we have problems with insufficient bandwidth please find attached requested photo displaying error we get error several times week when we start meetings with our clients we have also reported ticket with same message being provided by could you please evaluate if available bandwidth adequate for our latest number colleagues thank you for your have great consultant registered under number whose registered old broad street kingdom does provide any clients each subsidiaries separate entity liability for another such entity acts or,Hardware,92
47830,malfunction sent tuesday july re malfunction hi remark issue happens only computer colleagues computer program works fine also we tried change password but same message appears thank you sent tuesday july malfunction hi below error appears when try use could you please help with issue thank you specialist en address blvd th floor district registered under number whose registered old broad street kingdom does provide any clients each subsidiaries separate entity liability for another such entity acts,Hardware,77
47834,connection issues sent tuesday july connection issues hello have connection issues while working client side link connection type cable en using applications excel word explorer very slow with delays while moving mouse or clicking constant problem but today slower than usual impacting our work same for colleagues working problem have previously reported please advise thank you senior analyst ext,Hardware,59
47836,running out on extensions hello please be advised we running out extension least seems there more extension available range nor anything can be found range per following file extensions excel have found extension only because have found leaver removed could you please advise if there indeed extensions left thank you best regards,Hardware,52

In [ ]:
df.iloc[0, 0]

'connection with icon icon dear please setup icon per icon engineers please let other details needed thanks lead'